name: build-locally

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache  # Optional
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel
    - run: bazel build //...
    - name: run
      run: |
        # docker run -u 1000:1000 -v /tmp:/data -p 9090:8080 -p 9092:9092 quay.io/bazel-remote/bazel-remote
        python build-locally.py linux_64_c_compiler_version10cuda_compiler_version11.2cudnn8cxx_compiler_version10python3.10.____cpython
